### ISSUE TITLE
Konfigurasi Vmess

### ISSUE THREAD

**Issue by petapabiawak** [lutfailham96/libernet#1]
Bang, klo brkenan boleh gk di vmess nya dibagian buat konfignya diisi opsi untuk vmess support tls atau http dan juga /Path vmessnya bang gak ada , jdi mngkin di akun vmess tertentu saja yg bisa konek,, terima kasih

**Comment by lutfailham96** [comment]
> Bang, klo brkenan boleh gk di vmess nya dibagian buat konfignya diisi opsi untuk vmess support tls atau http dan juga /Path vmessnya bang gak ada , jdi mngkin di akun vmess tertentu saja yg bisa konek,, terima kasih

coba branch v1.1-devel, disitu sudah saya kasih opsi stream security untuk v2ray

**Comment by petapabiawak** [comment]
> > Bang, klo brkenan boleh gk di vmess nya dibagian buat konfignya diisi opsi untuk vmess support tls atau http dan juga /Path vmessnya bang gak ada , jdi mngkin di akun vmess tertentu saja yg bisa konek,, terima kasih
> 
> coba branch v1.1-devel, disitu sudah saya kasih opsi stream security untuk v2ray

straeaming setting di bagian network gk bisa diganti tcp jadi ws pak?? biar nanti bisa masukin pathnya

**Comment by lutfailham96** [comment]
> > > Bang, klo brkenan boleh gk di vmess nya dibagian buat konfignya diisi opsi untuk vmess support tls atau http dan juga /Path vmessnya bang gak ada , jdi mngkin di akun vmess tertentu saja yg bisa konek,, terima kasih
> > 
> > 
> > coba branch v1.1-devel, disitu sudah saya kasih opsi stream security untuk v2ray
> 
> straeaming setting di bagian network gk bisa diganti tcp jadi ws pak?? biar nanti bisa masukin pathnya

versi sekarang sudah support konfigurasi v2ray network, security & sni. silahkan update & dicoba.
