### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by hunternblz** [lutfailham96/libernet#10]
saya pake trojan saat server mereboot (closed by server), libernetnya nggak otomatis reconnect (bengong) jadi harus stop lalu start ulang baru lancar.

**Comment by lutfailham96** [comment]
> saya pake trojan saat server mereboot (closed by server), libernetnya nggak otomatis reconnect (bengong) jadi harus stop lalu start ulang baru lancar.

closed karena server reboot otomatis?

**Comment by hunternblz** [comment]
> > saya pake trojan saat server mereboot (closed by server), libernetnya nggak otomatis reconnect (bengong) jadi harus stop lalu start ulang baru lancar.
> 
> closed karena server reboot otomatis?

iya bener

**Comment by sachnun** [comment]
kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
trus manfaatin api dari web buat lakuin rekonek

agak kurang meyakinkan, tapi setidaknya membantu

`function go()
{
if ! ping -c 3 -I tun1 1.1.1.1
then
{
   echo "Reconnect"
   curl 'http://localhost/libernet/api.php' --data-raw '{"action":"stop_libernet"}' && sleep 5 && curl 'http://localhost/libernet/api.php' --data-raw '{"action":"start_libernet"}'
}
else
{
   echo "Aman"
}
fi
exit 0
}
go
`

**Comment by lutfailham96** [comment]
> kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> trus manfaatin api dari web buat lakuin rekonek
> 
> agak kurang meyakinkan, tapi setidaknya membantu
> https://codeshare.io/aJZjLd

iya bisa diakalin pakai cron, tapi sepertinya nanti paling efektif dibikin service loop seperti ssh saja

**Comment by hunternblz** [comment]
> kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> trus manfaatin api dari web buat lakuin rekonek
> 
> agak kurang meyakinkan, tapi setidaknya membantu
> https://codeshare.io/aJZjLd

thanks, sementara saya pake cronjob dulu

**Comment by hunternblz** [comment]
> > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > trus manfaatin api dari web buat lakuin rekonek
> > agak kurang meyakinkan, tapi setidaknya membantu
> > https://codeshare.io/aJZjLd
> 
> iya bisa diakalin pakai cron, tapi sepertinya nanti paling efektif dibikin service loop seperti ssh saja

ditunggu 😃

**Comment by lutfailham96** [comment]
> > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > trus manfaatin api dari web buat lakuin rekonek
> > agak kurang meyakinkan, tapi setidaknya membantu
> > https://codeshare.io/aJZjLd
> 
> thanks, sementara saya pake cronjob dulu

coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan

**Comment by hunternblz** [comment]
> > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > trus manfaatin api dari web buat lakuin rekonek
> > > agak kurang meyakinkan, tapi setidaknya membantu
> > > https://codeshare.io/aJZjLd
> > 
> > 
> > thanks, sementara saya pake cronjob dulu
> 
> coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan

udah update libernetnya, tapi tetap nggak mau otomatis reconnect.

![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)

**Comment by lutfailham96** [comment]
> > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > trus manfaatin api dari web buat lakuin rekonek
> > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > https://codeshare.io/aJZjLd
> > > 
> > > 
> > > thanks, sementara saya pake cronjob dulu
> > 
> > 
> > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> 
> udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> kalau pakai ssh langsung bisa auto reconnectnya
> 
> ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)

coba reboot & screenshot output masing-masing command ini
1. screen -list
2. ip route
3. cat /etc/rc.local

**Comment by hunternblz** [comment]
> > > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > > trus manfaatin api dari web buat lakuin rekonek
> > > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > > https://codeshare.io/aJZjLd
> > > > 
> > > > 
> > > > thanks, sementara saya pake cronjob dulu
> > > 
> > > 
> > > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> > 
> > 
> > udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> > kalau pakai ssh langsung bisa auto reconnectnya
> > ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)
> 
> coba reboot & screenshot output masing-masing command ini
> 
> 1. screen -list
> 2. ip route
> 3. cat /etc/rc.local

![Screenshot_20210323-141405](https://user-images.githubusercontent.com/34278783/112108058-503d5a80-8be2-11eb-942d-81db1399aa71.png)

**Comment by lutfailham96** [comment]
> > > > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > > > trus manfaatin api dari web buat lakuin rekonek
> > > > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > > > https://codeshare.io/aJZjLd
> > > > > 
> > > > > 
> > > > > thanks, sementara saya pake cronjob dulu
> > > > 
> > > > 
> > > > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> > > 
> > > 
> > > udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> > > kalau pakai ssh langsung bisa auto reconnectnya
> > > ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)
> > 
> > 
> > coba reboot & screenshot output masing-masing command ini
> > 
> > 1. screen -list
> > 2. ip route
> > 3. cat /etc/rc.local
> 
> ![Screenshot_20210323-141405](https://user-images.githubusercontent.com/34278783/112108058-503d5a80-8be2-11eb-942d-81db1399aa71.png)

auto start centang / coba simulasi closed by servernya

**Comment by hunternblz** [comment]
> > > > > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > > > > trus manfaatin api dari web buat lakuin rekonek
> > > > > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > > > > https://codeshare.io/aJZjLd
> > > > > > 
> > > > > > 
> > > > > > thanks, sementara saya pake cronjob dulu
> > > > > 
> > > > > 
> > > > > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> > > > 
> > > > 
> > > > udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> > > > kalau pakai ssh langsung bisa auto reconnectnya
> > > > ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)
> > > 
> > > 
> > > coba reboot & screenshot output masing-masing command ini
> > > 
> > > 1. screen -list
> > > 2. ip route
> > > 3. cat /etc/rc.local
> > 
> > 
> > ![Screenshot_20210323-141405](https://user-images.githubusercontent.com/34278783/112108058-503d5a80-8be2-11eb-942d-81db1399aa71.png)
> 
> auto start centang / coba simulasi closed by servernya

tetap

![Screenshot_20210323-142213](https://user-images.githubusercontent.com/34278783/112109376-153c2680-8be4-11eb-9d37-5a2535a1e20b.png)

![Screenshot_20210323-142524](https://user-images.githubusercontent.com/34278783/112109413-208f5200-8be4-11eb-9a37-5de1f9ab3398.png)

**Comment by lutfailham96** [comment]
> > > > > > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > > > > > trus manfaatin api dari web buat lakuin rekonek
> > > > > > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > > > > > https://codeshare.io/aJZjLd
> > > > > > > 
> > > > > > > 
> > > > > > > thanks, sementara saya pake cronjob dulu
> > > > > > 
> > > > > > 
> > > > > > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> > > > > 
> > > > > 
> > > > > udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> > > > > kalau pakai ssh langsung bisa auto reconnectnya
> > > > > ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)
> > > > 
> > > > 
> > > > coba reboot & screenshot output masing-masing command ini
> > > > 
> > > > 1. screen -list
> > > > 2. ip route
> > > > 3. cat /etc/rc.local
> > > 
> > > 
> > > ![Screenshot_20210323-141405](https://user-images.githubusercontent.com/34278783/112108058-503d5a80-8be2-11eb-942d-81db1399aa71.png)
> > 
> > 
> > auto start centang / coba simulasi closed by servernya
> 
> tetap
> 
> ![Screenshot_20210323-142213](https://user-images.githubusercontent.com/34278783/112109376-153c2680-8be4-11eb-9d37-5a2535a1e20b.png)
> 
> ![Screenshot_20210323-142524](https://user-images.githubusercontent.com/34278783/112109413-208f5200-8be4-11eb-9a37-5de1f9ab3398.png)

saya rasa ini masalah bukan dari aplikasinya , tapi dari jaringan isp / vpn yang bikin bengong.
trojan kategorinya proxy & harusnya tanpa tambahan loop bisa lancar, solusi paling cocok mungkin memang harus diakalin sendiri via cron

**Comment by hunternblz** [comment]
> > > > > > > > > kalo saya biasa ngatasinnya pakai bantuan cron job buat test ping ke tun1 / libernet interfacenya
> > > > > > > > > trus manfaatin api dari web buat lakuin rekonek
> > > > > > > > > agak kurang meyakinkan, tapi setidaknya membantu
> > > > > > > > > https://codeshare.io/aJZjLd
> > > > > > > > 
> > > > > > > > 
> > > > > > > > thanks, sementara saya pake cronjob dulu
> > > > > > > 
> > > > > > > 
> > > > > > > coba update yang sekarang, sepertinya sudah bisa fix problem reconnect trojan
> > > > > > 
> > > > > > 
> > > > > > udah update libernetnya, tapi tetap nggak mau otomatis reconnect.
> > > > > > kalau pakai ssh langsung bisa auto reconnectnya
> > > > > > ![Screenshot_20210323-070313](https://user-images.githubusercontent.com/34278783/112080198-1e150400-8bb4-11eb-8d8a-fbe528d7cba2.png)
> > > > > 
> > > > > 
> > > > > coba reboot & screenshot output masing-masing command ini
> > > > > 
> > > > > 1. screen -list
> > > > > 2. ip route
> > > > > 3. cat /etc/rc.local
> > > > 
> > > > 
> > > > ![Screenshot_20210323-141405](https://user-images.githubusercontent.com/34278783/112108058-503d5a80-8be2-11eb-942d-81db1399aa71.png)
> > > 
> > > 
> > > auto start centang / coba simulasi closed by servernya
> > 
> > 
> > tetap
> > ![Screenshot_20210323-142213](https://user-images.githubusercontent.com/34278783/112109376-153c2680-8be4-11eb-9d37-5a2535a1e20b.png)
> > ![Screenshot_20210323-142524](https://user-images.githubusercontent.com/34278783/112109413-208f5200-8be4-11eb-9a37-5de1f9ab3398.png)
> 
> saya rasa ini masalah bukan dari aplikasinya , tapi dari jaringan isp / vpn yang bikin bengong.
> trojan kategorinya proxy & harusnya tanpa tambahan loop bisa lancar, solusi paling cocok mungkin memang harus diakalin sendiri via cron

mungkin begitu.
saya pakein cron saja.

thanks
