### ISSUE TITLE
index.php download accessing http://router-ip/libernet

### ISSUE THREAD

**Issue by essoojay** [lutfailham96/libernet#11]
Platform: sunxi s905x openwrt
Installation: successful

Problem:

Cant access libernet configuation url, it downloads index.php

Steps tried: I cleared cookies, reinstall libernet, same problem

please how to fix

Thank you

**Comment by lutfailham96** [comment]
> Platform: sunxi s905x openwrt
> Installation: successful
> 
> Problem:
> 
> Cant access libernet configuation url, it downloads index.php
> 
> Steps tried: I cleared cookies, reinstall libernet, same problem
> 
> please how to fix
> 
> Thank you

you have to enable php execution manually, by putting php on uhttp list interpreter

**Comment by essoojay** [comment]
> > Platform: sunxi s905x openwrt
> > Installation: successful
> > Problem:
> > Cant access libernet configuation url, it downloads index.php
> > Steps tried: I cleared cookies, reinstall libernet, same problem
> > please how to fix
> > Thank you
> 
> you have to enable php execution manually, by putting php on uhttp list interpreter


____________

thanks, just for anyone with that issue, solution is 

edit      /etc/config/uhttpd

under config uhttpd main

add:  	list interpreter '.php=/usr/bin/php-cgi'

save and reboot
