### ISSUE TITLE
Add option to disable username/password auth

### ISSUE THREAD

**Issue by utoro** [lutfailham96/libernet#12]
When using OpenVPN config with the embedded private key, I am still required to enter an username & password.
https://prnt.sc/10utas5

Temporary solution: use space in username & password.

**Comment by lutfailham96** [comment]
> When using OpenVPN config with the embedded private key, I am still required to enter an username & password.
> https://prnt.sc/10utas5
> 
> Temporary solution: use space in username & password.

now you can update Libernet and using openvpn embedded private key without input any username & password
don't forget to clear browser cache to get change

**Comment by utoro** [comment]
> > When using OpenVPN config with the embedded private key, I am still required to enter an username & password.
> > https://prnt.sc/10utas5
> > Temporary solution: use space in username & password.
> 
> now you can update Libernet and using openvpn embedded private key without input any username & password
> don't forget to clear browser cache to get change

thanks, the updated version worked fine.
