### ISSUE TITLE
Request Penambahan Fitur

### ISSUE THREAD

**Issue by yusantama** [lutfailham96/libernet#16]
Mbah, tambahin jumlah bandwith upload+download dong deket status connected kalo bisa. Dan buat Libernet bisa bypass koneksi vpn by domain. Jadi ada domain yang ikut koneksi vpn sama ada domain yang ikut koneksi vpn...

**Comment by lutfailham96** [comment]
> Mbah, tambahin jumlah bandwith upload+download dong deket status connected kalo bisa. Dan buat Libernet bisa bypass koneksi vpn by domain. Jadi ada domain yang ikut koneksi vpn sama ada domain yang ikut koneksi vpn...

untuk yang bypass koneksi vpn mungkin bakal nunggu clue atau project lain yang serupa, karena kemungkinan tingkat kesulitan cukup tinggi

**Comment by yusantama** [comment]
> > Mbah, tambahin jumlah bandwith upload+download dong deket status connected kalo bisa. Dan buat Libernet bisa bypass koneksi vpn by domain. Jadi ada domain yang ikut koneksi vpn sama ada domain yang ikut koneksi vpn...
> 
> untuk yang bypass koneksi vpn mungkin bakal nunggu clue atau project lain yang serupa, karena kemungkinan tingkat kesulitan cukup tinggi

Yuk bisa yuk mbah hehe... bakal jadi tools pertama yang bisa bypass domain kalo kejadian nih. Btw buat referensi ada nih mbah, vpn policies nya gl-inet.

**Comment by lutfailham96** [comment]
> > > Mbah, tambahin jumlah bandwith upload+download dong deket status connected kalo bisa. Dan buat Libernet bisa bypass koneksi vpn by domain. Jadi ada domain yang ikut koneksi vpn sama ada domain yang ikut koneksi vpn...
> > 
> > 
> > untuk yang bypass koneksi vpn mungkin bakal nunggu clue atau project lain yang serupa, karena kemungkinan tingkat kesulitan cukup tinggi
> 
> Yuk bisa yuk mbah hehe... bakal jadi tools pertama yang bisa bypass domain kalo kejadian nih. Btw buat referensi ada nih mbah, vpn policies nya gl-inet.

bandwith upload (tx) download (rx) sudah bisa digunakan sekarang
