### ISSUE TITLE
Ping loop

### ISSUE THREAD

**Issue by Kry9toN** [lutfailham96/libernet#17]
Why you not make function auto stop and start in ping loop service?
Every 30 - 1hour connection is always missing

**Comment by lutfailham96** [comment]
> Why you not make function auto stop and start in ping loop service?
> Every 30 - 1hour connection is always missing

it is because ping loop service just using http request (head) on internet to keep connection keep alive, there's no problem on my device even it is always on 24h/day

**Comment by Kry9toN** [comment]
try to create a new service, for how many hours the libernet service stops and starts

That will help a lot of people

Thanks
