### ISSUE TITLE
Request Region WAN IP

### ISSUE THREAD

**Issue by cekra007** [lutfailham96/libernet#20]
mbah, tolong di update untuk menambahkan keterangan negara mana yg lagi dipake vpnnya, kalo ip saja tidak cukup untuk mengetahui lokasinya berada. semoga fitur ini tersedia di versi kedepan hehe. suwun mbah

**Comment by lutfailham96** [comment]
> mbah, tolong di update untuk menambahkan keterangan negara mana yg lagi dipake vpnnya, kalo ip saja tidak cukup untuk mengetahui lokasinya berada. semoga fitur ini tersedia di versi kedepan hehe. suwun mbah

versi terbaru sekarang sudah include ip country, silahkan dicek

**Comment by cekra007** [comment]
> > mbah, tolong di update untuk menambahkan keterangan negara mana yg lagi dipake vpnnya, kalo ip saja tidak cukup untuk mengetahui lokasinya berada. semoga fitur ini tersedia di versi kedepan hehe. suwun mbah
> 
> versi terbaru sekarang sudah include ip country, silahkan dicek

makasih gan udah di update, tapi di tempat saya setelah update tampilan index.php gak muncul dashboardnya, ngeblank gitu. sekarang lagi pake versi sebelumnya yg masih normal

**Comment by lutfailham96** [comment]
> > > mbah, tolong di update untuk menambahkan keterangan negara mana yg lagi dipake vpnnya, kalo ip saja tidak cukup untuk mengetahui lokasinya berada. semoga fitur ini tersedia di versi kedepan hehe. suwun mbah
> > 
> > 
> > versi terbaru sekarang sudah include ip country, silahkan dicek
> 
> makasih gan udah di update, tapi di tempat saya setelah update tampilan index.php gak muncul dashboardnya, ngeblank gitu. sekarang lagi pake versi sebelumnya yg masih normal

coba clear cache browser dulu

**Comment by cekra007** [comment]
> > > > mbah, tolong di update untuk menambahkan keterangan negara mana yg lagi dipake vpnnya, kalo ip saja tidak cukup untuk mengetahui lokasinya berada. semoga fitur ini tersedia di versi kedepan hehe. suwun mbah
> > > 
> > > 
> > > versi terbaru sekarang sudah include ip country, silahkan dicek
> > 
> > 
> > makasih gan udah di update, tapi di tempat saya setelah update tampilan index.php gak muncul dashboardnya, ngeblank gitu. sekarang lagi pake versi sebelumnya yg masih normal
> 
> coba clear cache browser dulu

eh iya bisa dibuka pas clear cache browser, terimakasih udah update fitur ini gan
