### ISSUE TITLE
V2RAY dan trojan stuck connecting device raspberry pi 3 model b+

### ISSUE THREAD

**Issue by ikhsanh** [lutfailham96/libernet#24]
file ipk v2ray saya ambil dari sini https://github.com/kuoruan/openwrt-v2ray (v2ray-core_4.37.3-1_aarch64_cortex-a53.ipk
), setelah semua selesai install, v2ray dan trojan stuck connecting terus, kemudian gagal. untuk tools yang lain (ss, ssh, openvpn) bisa digunakan. 

![Screenshot (145)](https://user-images.githubusercontent.com/39503448/116187669-1cf56a80-a750-11eb-9ce1-a162d8cd587e.png)
![Screenshot (144)](https://user-images.githubusercontent.com/39503448/116187672-2088f180-a750-11eb-8cc5-502460fc842f.png)

**Comment by lutfailham96** [comment]
> file ipk v2ray saya ambil dari sini https://github.com/kuoruan/openwrt-v2ray (v2ray-core_4.37.3-1_aarch64_cortex-a53.ipk
> ), setelah semua selesai install, v2ray dan trojan stuck connecting terus, kemudian gagal. untuk tools yang lain (ss, ssh, openvpn) bisa digunakan.
> 
> ![Screenshot (145)](https://user-images.githubusercontent.com/39503448/116187669-1cf56a80-a750-11eb-9ce1-a162d8cd587e.png)
> ![Screenshot (144)](https://user-images.githubusercontent.com/39503448/116187672-2088f180-a750-11eb-8cc5-502460fc842f.png)

coba didebug dulu via cli
v2ray -config /path_to_config.json

**Comment by laksa19** [comment]
@ikhsanh  boleh bagi firmware Raspinya dong, soalnya saya download dari website OpenWRT gak ada yang bisa, terima kasih

**Comment by lutfailham96** [comment]
> @ikhsanh boleh bagi firmware Raspinya dong, soalnya saya download dari website OpenWRT gak ada yang bisa, terima kasih

saya tidak ada device & firmwarenya

**Comment by laksa19** [comment]
kalau seperti ini masalah dibagian apa ya?
![image](https://user-images.githubusercontent.com/16347475/116486904-e6872f00-a8b8-11eb-9fda-deeffdc4d450.png)

**Comment by ikhsanh** [comment]
Solved. Saya salah memasukkan info akun v2ray. 
Untuk firmware nya bisa download disini
OPENWRT 19.07.0 RASPBERRY PI 3B+
Basic Information :
LuCI
Ip address ‘192.168.1.1/cgi-bin/luci’
Username/Password ‘root / root’
SSID : ‘OpenWrt’

GUI libernet
Ip address 'http://192.168.1.1/libernet/login.php
Username/Password 'admin/libernet'

Include Tunneling :
– Wireguard
– Shadowsocks OBFS
– Shadowsocks CLOAK
- ShadowsocksR
– Openvpn 
– L2TP 
- V2Ray

Installed : 
- 3g/4G info
- Modem Overview
- Atinout
- QMI Modem ( support modem hplt4220) plug and play
https://drive.google.com/file/d/1MIZrM-fXAx6FyaYVuReR_H6erss_yRqd/view?usp=sharing
