### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by odie84** [lutfailham96/libernet#28]
Untuk mendapatkan ip kadang harus merestart interface hilink.

**Comment by lutfailham96** [comment]
> Untuk mendapatkan ip kadang harus merestart interface hilink.

yang dimaksud ip interface apa?

**Comment by odie84** [comment]
> 
> 
> > Untuk mendapatkan ip kadang harus merestart interface hilink.
> 
> yang dimaksud ip interface apa?

Ip provider ... di interface Hilink. kadang harus di restart dulu interface hilinknya...

**Comment by lutfailham96** [comment]
> > > Untuk mendapatkan ip kadang harus merestart interface hilink.
> > 
> > 
> > yang dimaksud ip interface apa?
> 
> Ip provider ... di interface Hilink. kadang harus di restart dulu interface hilinknya...

kalau itu sudah di luar cakupan libernet, bisa saja openwrt yang dipakai masih ada bug
