### ISSUE TITLE
Tambahin fitur nama operator

### ISSUE THREAD

**Issue by odie84** [lutfailham96/libernet#30]
Tolong tambahin fitur nama operator biar keliatan sc yg di gunakan. Terimakasih

**Comment by lutfailham96** [comment]
> Tolong tambahin fitur nama operator biar keliatan sc yg di gunakan. Terimakasih

sudah ditambah, silahkan dicoba

**Comment by odie84** [comment]
> > Tolong tambahin fitur nama operator biar keliatan sc yg di gunakan. Terimakasih
> 
> sudah ditambah, silahkan dicoba

terimakasih
