### ISSUE TITLE
No Internet - Sebelumnya Lancar - Raspi 3 

### ISSUE THREAD

**Issue by venturazz** [lutfailham96/libernet#42]
**Kak ini artinya apa ya? Sebelumnya lancar tanpa kendala tapi beberapa waktu lalu jadi No Internet.**

Thu Mar 31 17:31:17 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:31:18 2022 daemon.err uhttpd[917]: /root/libernet/bin/service.sh: line 27: echo: write error: Broken pipe
Thu Mar 31 17:31:18 2022 daemon.err uhttpd[917]: /root/libernet/bin/service.sh: line 31: echo: write error: Broken pipe
Thu Mar 31 17:31:18 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:31:18 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:31:19 2022 daemon.notice netifd: Interface 'libernet' is enabled
Thu Mar 31 17:31:19 2022 daemon.err uhttpd[917]: /root/libernet/bin/tun2socks.sh: line 44: echo: write error: Broken pipe
Thu Mar 31 17:31:19 2022 daemon.err uhttpd[917]: /root/libernet/bin/tun2socks.sh: line 101: echo: write error: Broken pipe
Thu Mar 31 17:31:19 2022 daemon.err uhttpd[917]: /root/libernet/bin/tun2socks.sh: line 69: echo: write error: Broken pipe
Thu Mar 31 17:31:19 2022 daemon.err uhttpd[917]: /root/libernet/bin/service.sh: line 190: echo: write error: Broken pipe
Thu Mar 31 17:32:01 2022 daemon.err uhttpd[917]: killall: python3: no process killed
Thu Mar 31 17:32:03 2022 daemon.err uhttpd[917]: kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Thu Mar 31 17:32:03 2022 daemon.notice netifd: Interface 'libernet' is disabled
Thu Mar 31 17:32:03 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:03 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:04 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:04 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:05 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:05 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:06 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:06 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:07 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:07 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:08 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found
Thu Mar 31 17:32:08 2022 daemon.err uhttpd[917]: ifconfig: tun1: error fetching interface information: Device not found

**Catatan : Selain tun1 device not found juga broken pipe.** Terima Kasih sebelumnya Kak.

**Comment by afwajames910** [comment]
@venturazz bro you found any sloution?
