### ISSUE TITLE
openwrt ifconfig: tun1: error fetching interface information: device not found

### ISSUE THREAD

**Issue by Erwingwapo999** [lutfailham96/libernet#48]
This shows in the system log bro.
And Kmod-tun is alreaady installed 

**_openwrt ifconfig: tun1: error fetching interface information: device not found_
**
please help! Heres my firmware version bro[Screenshot_2023-01-01-21-21-12-102_com.kiwibrowser.browser.png](https://user-images.githubusercontent.com/57695347/210172083-af92cd61-471a-49b0-91cb-1e41e0fb6119.png)

**Comment by afwajames910** [comment]
@Erwingwapo999 bro you found any sloution?
