### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by afwajames910** [lutfailham96/libernet#51]
Hello, please help me.
I installed openwrt 22.03.5 and after then i connect router with
wireless wifi with 802.11bgn (radio1).
then i installed libernet.

afer installing libernet i received 'radio0' is disabled.
i create config and click on start button, but its not working.
i am new, where is the problem in Interfaces?
please check attached screenshots.
![1](https://github.com/lutfailham96/libernet/assets/132413598/1a8fabeb-c2ed-42aa-b530-244560e4a685)
![2](https://github.com/lutfailham96/libernet/assets/132413598/6e2f8f1d-79ee-4efe-9e17-458098a3b238)
![3](https://github.com/lutfailham96/libernet/assets/132413598/8b1956ea-d465-45d1-923f-6e4b8f77b1ab)

**Comment by afwajames910** [comment]
logs:
Tue May  9 23:35:03 2023 daemon.err uhttpd[22689]: ifconfig: tun1: error fetching interface information: Device not found

**Comment by ingnelson** [comment]
I have the same problem
