### ISSUE TITLE
Not detec't WAN IP

### ISSUE THREAD

**Issue by aldisyah02** [lutfailham96/libernet#7]
Hello Sir

i just wanna ask you about my issue i faced.
so when i install the libernet , the libernet not detect WAN IP and because that, i can't start the libernet

plz help me ;(

regard

**Comment by aldisyah02** [comment]
ok the wan ip is empty but the newest version fix the feature and i can use the libernet

**Comment by lutfailham96** [comment]
If you're using public server, usually ip checker server will block the request because of huge requests & you'll not get wan ip. try to use paid & your own server
