### ISSUE TITLE
Install error libernet Raspberry Pi 4

### ISSUE THREAD

**Issue by helmiau** [lutfailham96/libernet#8]
Upgrading ip-full on root from 5.7.0-2 to 5.11.0-1...
Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/ip-full_5.11.0-1_aarch64_cortex-a72.ipk
Installing libnl-tiny1 (2020-08-05-c291088f-1) to root...
Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libnl-tiny1_2020-08-05-c291088f-1_aarch64_cortex-a72.ipk
Collected errors:
 * check_data_file_clashes: Package libnl-tiny1 wants to install file /usr/lib/libnl-tiny.so
        But that file is already provided by package  * libnl-tiny
 * opkg_install_cmd: Cannot install package ip-full.
 
##############################
error above fixed by this ```opkg remove libnl-tiny```
##############################
 root@OpenWrt:~/Downloads/libernet# opkg remove libnl-tiny
No packages removed.
Collected errors:
 * print_dependents_warning: Package libnl-tiny is depended upon by packages:
 * print_dependents_warning:    iw
 * print_dependents_warning:    luci-lib-ip
 * print_dependents_warning:    ip-full
 * print_dependents_warning:    wpad-basic-wolfssl
 * print_dependents_warning:    netifd
 * print_dependents_warning:    nlbwmon
 * print_dependents_warning:    libiwinfo20200105
 * print_dependents_warning: These might cease to work if package libnl-tiny is removed.
 * print_dependents_warning: Force removal of this package with --force-depends.
 * print_dependents_warning: Force removal of this package and its dependents
 * print_dependents_warning: with --force-removal-of-dependent-packages.
root@OpenWrt:~/Downloads/libernet# opkg remove libnl-tiny --force-depends && opkg install ip-full libnl-tiny1
Removing package libnl-tiny from root...
Upgrading ip-full on root from 5.7.0-2 to 5.11.0-1...
Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/ip-full_5.11.0-1_aarch64_cortex-a72.ipk
Installing libnl-tiny1 (2020-08-05-c291088f-1) to root...
Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libnl-tiny1_2020-08-05-c291088f-1_aarch64_cortex-a72.ipk
Installing libbpf0 (5.11.2-1) to root...masih nunggu 
Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libbpf0_5.11.2-1_aarch64_cortex-a72.ipk
Package libnl-tiny1 (2020-08-05-c291088f-1) installed in root is up to date.
Configuring libnl-tiny1.
Configuring libbpf0.
Configuring ip-full.
root@OpenWrt:~/Downloads/libernet#

########################################
then this error shown
########################################

Copying proprietary binaries
cp: can't stat 'proprietary/aarch64_cortex-a72/binaries/*': No such file or directory

**Comment by lutfailham96** [comment]
> Upgrading ip-full on root from 5.7.0-2 to 5.11.0-1...
> Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/ip-full_5.11.0-1_aarch64_cortex-a72.ipk
> Installing libnl-tiny1 (2020-08-05-c291088f-1) to root...
> Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libnl-tiny1_2020-08-05-c291088f-1_aarch64_cortex-a72.ipk
> Collected errors:
> 
> * check_data_file_clashes: Package libnl-tiny1 wants to install file /usr/lib/libnl-tiny.so
>   But that file is already provided by package  * libnl-tiny
> * opkg_install_cmd: Cannot install package ip-full.
> 
> ##############################
> error above fixed by this `opkg remove libnl-tiny`
> ##############################
> root@OpenWrt:~/Downloads/libernet# opkg remove libnl-tiny
> No packages removed.
> Collected errors:
> 
> * print_dependents_warning: Package libnl-tiny is depended upon by packages:
> * print_dependents_warning:    iw
> * print_dependents_warning:    luci-lib-ip
> * print_dependents_warning:    ip-full
> * print_dependents_warning:    wpad-basic-wolfssl
> * print_dependents_warning:    netifd
> * print_dependents_warning:    nlbwmon
> * print_dependents_warning:    libiwinfo20200105
> * print_dependents_warning: These might cease to work if package libnl-tiny is removed.
> * print_dependents_warning: Force removal of this package with --force-depends.
> * print_dependents_warning: Force removal of this package and its dependents
> * print_dependents_warning: with --force-removal-of-dependent-packages.
>   root@OpenWrt:~/Downloads/libernet# opkg remove libnl-tiny --force-depends && opkg install ip-full libnl-tiny1
>   Removing package libnl-tiny from root...
>   Upgrading ip-full on root from 5.7.0-2 to 5.11.0-1...
>   Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/ip-full_5.11.0-1_aarch64_cortex-a72.ipk
>   Installing libnl-tiny1 (2020-08-05-c291088f-1) to root...
>   Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libnl-tiny1_2020-08-05-c291088f-1_aarch64_cortex-a72.ipk
>   Installing libbpf0 (5.11.2-1) to root...masih nunggu
>   Downloading https://mirrors.cloud.tencent.com/openwrt/snapshots/packages/aarch64_cortex-a72/base/libbpf0_5.11.2-1_aarch64_cortex-a72.ipk
>   Package libnl-tiny1 (2020-08-05-c291088f-1) installed in root is up to date.
>   Configuring libnl-tiny1.
>   Configuring libbpf0.
>   Configuring ip-full.
>   root@OpenWrt:~/Downloads/libernet#
> 
> ########################################
> then this error shown
> ########################################
> 
> Copying proprietary binaries
> cp: can't stat 'proprietary/aarch64_cortex-a72/binaries/*': No such file or directory

buat folder aarch64_cortex-a72 di proprietary, nanti taruh semua binary dan package yang compatible dengan raspberry pi 4 disana.
